before:
  hooks:

builds:
  -
    id: build
    main: ./cmd/aserto-test
    binary: aserto-test
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto-test/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/aserto-test/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto-test/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - README.md
    name_template: "aserto-test_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: aserto-dev
    name: aserto-test

  draft: false
  prerelease: false
  name_template: "Aserto Test {{.Tag}}"

brews:
  -
    name: aserto-test

    tap:
      owner: aserto-dev
      name: aserto-tap
      token: "{{ .Env.HOMEBREW_TAP }}"

    url_template: "https://github.com/aserto-dev/aserto-test/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    download_strategy: CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "lib/custom_download_strategy"

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://aserto.com/"

    description: "Aserto Test Runner"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/aserto-test version"

    install: |
      bin.install "aserto-test"
