before:
  hooks:

builds:
  -
    id: build
    main: ./cmd/aserto-test
    binary: aserto-test
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto-test/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/aserto-test/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto-test/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE.md
      - README.md
    name_template: "aserto-test_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  disable: true

blobs:
  -
    provider: gs
    bucket: aserto-cli
    folder: "aserto-test/{{ .Version }}"
    extra_files:
      - glob: VERSION.txt
  -
    provider: gs
    bucket: aserto-cli
    folder: "aserto-test/latest"
    extra_files:
      - glob: VERSION.txt

brews:
  -
    name: aserto-test

    tap:
      owner: aserto-dev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP }}"

    url_template: "https://storage.googleapis.com/aserto-cli/aserto-test/{{ .Version }}/{{ .ArtifactName }}"

    download_strategy: CurlDownloadStrategy

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://docs.aserto.com/"

    description: "Aserto Test Runner"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/aserto-test version"

    install: |
      bin.install "aserto-test"
